{% set name = "Flask-Caching" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 3300efccda359d69ce0e6824b90cb571ff895a3907c31266c0342cca4bc40340

build:
  number: 0
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv '

requirements:
  host:
    - python >=3.7
    - pip
  run:
    - python >=3.7
    - flask <=2.1.2
    - cachelib <=0.6.0
    - markupsafe
    - werkzeug

test:
  imports:
    - flask_caching
    - flask_caching.backends
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sh4nks/flask-caching
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Adds caching support to your Flask application
  doc_url: https://pythonhosted.org/Flask-Caching
  dev_url: https://github.com/sh4nks/flask-caching

extra:
  recipe-maintainers:
    - halldc
    - ap--
